name: ff_trycatch
description: A utility class that provides helper methods for performing error handling and exception handling in synchronous and asynchronous operations.

version: 1.0.3
repository: https://github.com/flutterfocus/packages-dart-trycatch

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
